<a href="https://colab.research.google.com/github/cris-her/AI/blob/master/logistic_regression_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !/usr/bin/python
# -*-coding: utf -8 -*-

'''
i=1
mensaje = 'Hola' if i==1 else 'Adios'
print(mensaje)
'''

"\ni=1\nmensaje = 'Hola' if i==1 else 'Adios'\nprint(mensaje)\n"

In [2]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [3]:
x = np.array([0.5, 0.75, 1, 1.25, 1.5, 1.75, 1.75, 2, 2.25, 2.5,
              2.75, 3, 3.25, 3.5, 4, 4.25, 4.5, 4.75, 5, 5.5]).reshape(-1, 1)

y = np.array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [4]:
logistic_regression = LogisticRegression()

In [5]:
# Training the data
logistic_regression.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
# Test results
new_x = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)

prediction = logistic_regression.predict(new_x)
print("prediction:\n", prediction)

prediction:
 [0 0 1 1 1 1]


In [7]:
prediction_probabilities = logistic_regression.predict_proba(new_x)
print("prediction_probabilities:\n", prediction_probabilities)

prediction_probabilities:
 [[0.87984046 0.12015954]
 [0.69895285 0.30104715]
 [0.42402118 0.57597882]
 [0.18924992 0.81075008]
 [0.06891381 0.93108619]
 [0.02293029 0.97706971]]


In [8]:
print(prediction_probabilities[:, 1])

[0.12015954 0.30104715 0.57597882 0.81075008 0.93108619 0.97706971]
